name: structured_data
version: 2.0.0
description: A collection of functions for parsing structured data from web pages or local html documents
homepage: https://github.com/Appsolutely-Wonderful/dart_structured_data
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  html: ^0.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

